//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSDP.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassDate
    {
        public int ClassDateID { get; set; }
        public int StoreClassID { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual StoreClass StoreClass { get; set; }
    }
}
