//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSDP.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassDate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassDate()
        {
            this.ClassSignUps = new HashSet<ClassSignUp>();
        }
    
        public int ClassDateID { get; set; }
        public int StoreClassID { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<byte> ClassLimit { get; set; }
    
        public virtual StoreClass StoreClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassSignUp> ClassSignUps { get; set; }
    }
}
